"""empty message

Revision ID: 44641d86ff86
Revises: f3ae826cff7e
Create Date: 2021-04-24 21:13:42.001937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44641d86ff86'
down_revision = 'f3ae826cff7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'questions', 'categories', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    # ### end Alembic commands ###
